---
- name: install common packages
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - build-essential
    - git
    - mercurial
    - supervisor
    - unzip
    - curl
    - wget
